### ISSUE TITLE
Sending error

### ISSUE THREAD

**Issue by jvanremoortere** [responsiv/campaign-plugin#4] opened 2015-12-06 17:35 UTC
First of all great work! Amazing plugin.

But I can't seem to be able to send a campaign. Test messages work but when I try to send a campaign I get an error after a couple of minutes "Oops! It looks like your campaign hasn't got any subscribers... You can restore this campaign and try launching it again."

**Comment by daftspunk** [comment] 2015-12-07 23:00
Just check to make sure your subscribers are confirmed. If they are unconfirmed they won't be added to the campaign.

**Comment by jvanremoortere** [comment] 2015-12-07 23:38
How does that work? You can create subscribers manually but the fields "confirmed IP address" and "confirmed date" are not fillable (they are disabled)

**Comment by daftspunk** [comment] 2015-12-08 08:41
Ah yes, thanks for pointing this out. We had only added subscribers by import and using the signup component.

Update to the latest version (v1.1.9) for the fix. There should now be a checkbox saying "Mark as confirmed" when creating new subscribers manually in the back-end.

**Comment by jvanremoortere** [comment] 2015-12-08 10:39
Thanks. I've updated the plugin and it works now (for new subscribers).

Does it use soft delete? I've deleted the subscribers that I previously added manually and tried to add them again but for these subscribers the confirmation doesn't work.

**Comment by jvanremoortere** [comment] 2015-12-08 10:43
I see what happens now.

When you add a subscriber manually it redirects to the update page for that certain subscriber.
If you then update the subscriber the confirmation date gets erased. This is also true for other subscribers when updating them.

**Comment by daftspunk** [comment] 2015-12-08 20:50
Interesting observation. It doesn't seem to occur with the Created Date which is even more interesting. We will do some investigation and find out what's happening.

**Comment by daftspunk** [comment] 2015-12-08 21:20
Looks like this is a bug with October itself, it will be fixed in the next build, or in the meantime you can patch your code base manually from this commit: https://github.com/octobercms/october/commit/a186a60c436b3ee3653ee8b55dbd2c5dd877f34f

**Comment by jvanremoortere** [comment] 2015-12-08 21:32
Awesome. Thanks

**Closed as completed** 2016-02-23 00:04 UTC
